/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

 export interface paths {
    "/state": {
      /** Information about server parameters. Can be used as ping */
      get: operations["getServerState"];
    };
    "/users": {
      get: operations["getUsers"];
    };
    "/users/{userUid}": {
      get: operations["getUserInfo"];
    };
    "/users/me": {
      get: operations["getMyInfo"];
    };
    "/invites/": {
      /** Used and unused invitation codes */
      get: operations["getInvites"];
    };
  }
  
  export interface components {
    schemas: {
      Base:
        | { [key: string]: unknown }
        | {
            uid?: string;
            created_at?: string;
            updated_at?: string;
          }
        | {
            uid?: string;
            created_at?: string;
            updated_at?: string;
            deleted?: boolean;
          };
      User: components["schemas"]["Base"] & {
        name?: string;
        timezone?: string;
        ext?: {
          icon?: string;
          bot?: string;
        };
      };
      Invite: {
        code?: string;
        created_at?: string;
        used_at?: string;
        invitee?: string;
      };
    };
    parameters: {
      userUid: string;
    };
  }
  
  export interface operations {
    /** Information about server parameters. Can be used as ping */
    getServerState: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": {
              time?: string;
              extensions?: string[];
            };
          };
        };
      };
    };
    getUsers: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["User"][];
          };
        };
      };
    };
    getUserInfo: {
      parameters: {
        path: {
          userUid: components["parameters"]["userUid"];
        };
      };
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    getMyInfo: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["User"];
          };
        };
      };
    };
    /** Used and unused invitation codes */
    getInvites: {
      responses: {
        /** OK */
        200: {
          content: {
            "application/json": components["schemas"]["Invite"];
          };
        };
      };
    };
  }
  
  export interface external {}